---

# -- name of dataset and location
name: lycos2017
tabular: True
data_path: ~/data/lycos.csv

# -- columns to drop to prevent dataleak due to labelling method
drop:
    - flow_id
    - src_addr
    - src_port
    - dst_addr
    - dst_port
    - ip_prot
    - timestamp
    
    
# -- dataset information
n_features: 72
n_classes: 12
n_numeric: 72
n_cat: 0
n_cats: []

# -- split info
sample_thres: 100  # drop classes with less than this number of samples
train_ratio: 0.5
val_ratio: 0.
test_ratio: 0.5
split_seed: 39058032

# -- misc 
target: label # name of label column
class_zero: benign
batch_size: ${hyperparameters.batch_size}
balance_train: True
